"""add_shift_cash_management

Revision ID: 40952b16f974
Revises: d5e3f9a0b1c2
Create Date: 2026-04-28 09:28:36.274582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '40952b16f974'
down_revision: Union[str, Sequence[str], None] = 'd5e3f9a0b1c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('shift_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order', 'shift', ['shift_id'], ['id'])
    op.add_column('shift', sa.Column('initial_cash', sa.Float(), nullable=False))
    op.add_column('shift', sa.Column('expected_cash', sa.Float(), nullable=False))
    op.add_column('shift', sa.Column('actual_cash', sa.Float(), nullable=False))
    op.add_column('shift', sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shift', 'notes')
    op.drop_column('shift', 'actual_cash')
    op.drop_column('shift', 'expected_cash')
    op.drop_column('shift', 'initial_cash')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'shift_id')
    # ### end Alembic commands ###
